language: cpp
compiler:
  - clang
  - gcc

# Setup different environments to test
env:
  global:
    - LIBSTDC_VERSION=4.8
    - CLANG_VERSION=3.5

# Setup repos etc before installation
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - if [ "$CXX" == "clang++" ];  then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list; fi
  - if [ "$CXX" == "clang++" ];  then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-${CLANG_VERSION} main" | sudo tee -a /etc/apt/sources.list; fi
  - if [ "$CXX" == "clang++" ];  then echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list; fi
  - sudo apt-get update -qq

# Install dependencies
install:
  - sudo apt-get -qq install build-essential
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-${LIBSTDC_VERSION}; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${LIBSTDC_VERSION} 50; fi
  - if [ "$CXX" == "g++" ]; then CXX=g++-${LIBSTDC_VERSION}; fi
  
  - if [ "$CXX" == "clang++" ]; then sudo apt-get -qq --allow-unauthenticated install libstdc++-${LIBSTDC_VERSION}-dev; fi
  - if [ "$CXX" == "clang++" ]; then sudo apt-get -qq --allow-unauthenticated install clang-${CLANG_VERSION}; fi
  - if [ "$CXX" == "clang++" ]; then CXX=clang++-${CLANG_VERSION}; fi

# command to run tests
script: 
  - clang++ --version
  - cmake ./
  - make
  - if [ "`echo $CXX`" == "g++" ]; then ctest -C debug; fi